### ISSUE TITLE
ChineseName for languages

### ISSUE THREAD

**Issue by chrzyki** [lexibank/abrahammonpa#16]
The `CustomLanguage` class defines a [ChineseName](https://github.com/lexibank/abrahammonpa/blob/edb19f4a28267ea584d40e5933928e7f5b89a561/lexibank_abrahammonpa.py#L16) column that doesn't seem to be used right now. Should this information still be added or can the column be removed?

**Comment by LinguList** [comment]
If there's no info in the original data: remove it.

**Comment by chrzyki** [comment]
Thanks, done & removed.
